### ISSUE TITLE
Final test of the contracts

### ISSUE THREAD

**Issue by randomiserr** [weweswap/contracts#87]

**Comment by randomiserr** [comment]
- [ ] Can merge
- [ ] Merge vests the right amount of FOMO tokens
- [ ] The merged FOMO tokens are automatically sold on the market
- [ ] After selling FOMO, WEWE is bought
- [ ] Can claim the vested WEWE tokens

- [ ] Can sweep remaining WEWE from the contract
- [ ] Can change the owner, treasury, adaptor
- [ ] Can pause and unpause the contract

**Comment by bitcoinbrisbane** [comment]
Deployed => 0x310Dd8BE3f1DDCd28923a01DC771790324810c8E

**Comment by bitcoinbrisbane** [comment]
Need to test white lists
