### ISSUE TITLE
FOMO Merger Contract

### ISSUE THREAD

**Issue by randomiserr** [weweswap/contracts#89]
- [x] Can merge
- [x] Merge vests the right amount of FOMO tokens
- [x] The merged FOMO tokens are automatically sold on the market
- [x] After selling FOMO, WEWE is bought
- [x] Can claim the vested WEWE tokens
- [x] Can sweep remaining WEWE from the contract
- [x] Can change the owner, treasury, adaptor
- [x] Can add a whitelist
- [x] Can pause and unpause the contract

**Comment by bitcoinbrisbane** [comment]
Done.
